[package]
name = "player"
version = "0.1.0"
edition = "2018"

[features]
bundle_before = ["before"]

[dependencies]
serde_json = "1.0.64"
lru = "0.6.6"
rand = "0.8.4"
open = "1"

[dependencies.blaseball_vcr]
path = "../vcr_lib"

[dependencies.before]
git = "https://github.com/iliana/before.git"
branch = "main"
optional = true
default-features = false

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[[bin]]
name = "player"
path = "src/server.rs"
