[package]
name = "blaseball_vcr"
version = "0.1.0"
edition = "2018"

[dependencies]
json-patch = "0.2.6"
rmp-serde = "0.15.5"
xdelta3 = "0.1.5"
zstd = "0.9"
crossbeam = "0.8.1"

[dependencies.reqwest]
version = "0.11.4"
default-features = false

[dependencies.rocket]
version = "0.5.0-rc.1"

[dependencies.uuid]
version = "0.8.2"
features = ["serde"]

[dependencies.qp-trie]
version = "0.7.6"
features = ["serde"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.64"
features = ["preserve_order"]
